#define _XOPEN_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>

#include "common.h"

/*
 * See bits/confname.h.
 */
#define ENTRY(e) { (e), #e }

struct conf_entry {
	int number;
	char *name;
} static conf[] = {
	ENTRY(_CS_PATH),
	ENTRY(_CS_V6_WIDTH_RESTRICTED_ENVS),
	ENTRY(_CS_GNU_LIBC_VERSION),
	ENTRY(_CS_GNU_LIBPTHREAD_VERSION),
	ENTRY(_CS_V5_WIDTH_RESTRICTED_ENVS),
	ENTRY(_CS_V7_WIDTH_RESTRICTED_ENVS),
	ENTRY(_CS_LFS_CFLAGS),
	ENTRY(_CS_LFS_LDFLAGS),
	ENTRY(_CS_LFS_LIBS),
	ENTRY(_CS_LFS_LINTFLAGS),
	ENTRY(_CS_LFS64_CFLAGS),
	ENTRY(_CS_LFS64_LDFLAGS),
	ENTRY(_CS_LFS64_LIBS),
	ENTRY(_CS_LFS64_LINTFLAGS),
	ENTRY(_CS_XBS5_ILP32_OFF32_CFLAGS),
	ENTRY(_CS_XBS5_ILP32_OFF32_LDFLAGS),
	ENTRY(_CS_XBS5_ILP32_OFF32_LIBS),
	ENTRY(_CS_XBS5_ILP32_OFF32_LINTFLAGS),
	ENTRY(_CS_XBS5_ILP32_OFFBIG_CFLAGS),
	ENTRY(_CS_XBS5_ILP32_OFFBIG_LDFLAGS),
	ENTRY(_CS_XBS5_ILP32_OFFBIG_LIBS),
	ENTRY(_CS_XBS5_ILP32_OFFBIG_LINTFLAGS),
	ENTRY(_CS_XBS5_LP64_OFF64_CFLAGS),
	ENTRY(_CS_XBS5_LP64_OFF64_LDFLAGS),
	ENTRY(_CS_XBS5_LP64_OFF64_LIBS),
	ENTRY(_CS_XBS5_LP64_OFF64_LINTFLAGS),
	ENTRY(_CS_XBS5_LPBIG_OFFBIG_CFLAGS),
	ENTRY(_CS_XBS5_LPBIG_OFFBIG_LDFLAGS),
	ENTRY(_CS_XBS5_LPBIG_OFFBIG_LIBS),
	ENTRY(_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS),
	ENTRY(_CS_POSIX_V6_ILP32_OFF32_CFLAGS),
	ENTRY(_CS_POSIX_V6_ILP32_OFF32_LDFLAGS),
	ENTRY(_CS_POSIX_V6_ILP32_OFF32_LIBS),
	ENTRY(_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS),
	ENTRY(_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS),
	ENTRY(_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS),
	ENTRY(_CS_POSIX_V6_ILP32_OFFBIG_LIBS),
	ENTRY(_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS),
	ENTRY(_CS_POSIX_V6_LP64_OFF64_CFLAGS),
	ENTRY(_CS_POSIX_V6_LP64_OFF64_LDFLAGS),
	ENTRY(_CS_POSIX_V6_LP64_OFF64_LIBS),
	ENTRY(_CS_POSIX_V6_LP64_OFF64_LINTFLAGS),
	ENTRY(_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS),
	ENTRY(_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS),
	ENTRY(_CS_POSIX_V6_LPBIG_OFFBIG_LIBS),
	ENTRY(_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS),
	ENTRY(_CS_POSIX_V7_ILP32_OFF32_CFLAGS),
	ENTRY(_CS_POSIX_V7_ILP32_OFF32_LDFLAGS),
	ENTRY(_CS_POSIX_V7_ILP32_OFF32_LIBS),
	ENTRY(_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS),
	ENTRY(_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS),
	ENTRY(_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS),
	ENTRY(_CS_POSIX_V7_ILP32_OFFBIG_LIBS),
	ENTRY(_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS),
	ENTRY(_CS_POSIX_V7_LP64_OFF64_CFLAGS),
	ENTRY(_CS_POSIX_V7_LP64_OFF64_LDFLAGS),
	ENTRY(_CS_POSIX_V7_LP64_OFF64_LIBS),
	ENTRY(_CS_POSIX_V7_LP64_OFF64_LINTFLAGS),
	ENTRY(_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS),
	ENTRY(_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS),
	ENTRY(_CS_POSIX_V7_LPBIG_OFFBIG_LIBS),
	ENTRY(_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS),
	ENTRY(_CS_V6_ENV),
	ENTRY(_CS_V7_ENV),
};

int main(int argc, char *argv[])
{
	struct conf_entry *e;
	char buf[1024];
	int i;

	if (argc == 1) {
		for (e = ARRAY_BEGIN(conf); e < ARRAY_END(conf); e++) {
			errno = 0;
			confstr(e->number, buf, sizeof(buf));
			if (errno)
				continue;

			log("%-36s %4d = %s\n", e->name, e->number, buf);
		}

		return 0;
	}

	if (argv[1][0] == '-' && argv[1][1] == 'b') {
		for (i = 0; i < 64 * 1024; i++) {
			errno = 0;
			confstr(i, buf, sizeof(buf));
			if (errno)
				continue;

			log("%05d = %s\n", i, buf);
		}

		return 0;
	}

	return 1;
}
